config/routes.rb
# TODO: Need to review and limit routes to only those methods that are implemented (eg using 'only')
# TODO: Need to review and set the method (POST vs GET va DELETE) appropriately
Mankatha::Application.routes.draw do
  root :to => 'expense_reimbursements#index'

  resources :users, :only => [:new, :create]
  resources :sessions, :only => [:new, :create, :destroy]     # TODO: Usually, you dont expose the session directly - its just a mechanism to validate and carry current login state

  resources :forex_payments do
    collection do
      get :export
      get :data_to_suggest
    end
    member do
      get :clone
    end
  end

  resources :forex_reports, :only => [:index] do
    collection do
      get :export
    end
  end

  resources :outbound_travels do
    collection do
      get :export
      get :data_to_suggest
      get :get_recent
      get :travels_without_return_date
    end
    member do
      post :update_field
    end
  end

  resources :expense_settlements do
    collection do
      get  :show_uploads
      post :generate_report
      post :file_upload
      post :delete_cash_handover
      delete :delete_expense
    end
    member do
      get :load_by_travel
      post :notify
      post :set_processed
    end
  end

  resources :consolidated_expenses, :only => [:index] do
    collection do
      get :export
      post :mark_processed_and_export
    end
  end

  resources :expense_reimbursements, :only => [:index, :show, :edit] do
    collection do
      post :process_reimbursement
    end
  end

  resources :profiles, :only => [] do
    collection do
      get :search_by_name
      get :search_by_id
    end
  end

  resources :reports, :only => [:index]
end

app/models/outbound_travel.rb
class OutboundTravel
  include Mongoid::Document

  field :emp_id, type: Integer    #TODO: Why is this in a different type than in other models? Also, why the different names?
  field :emp_name    #TODO: Why does this have a different name than in other models?
  field :place
  field :travel_duration
  field :payroll_effect
  field :departure_date, type: Date
  field :foreign_payroll_transfer
  field :return_date, type: Date
  field :return_payroll_transfer
  # TODO: Can this record exist without an expected_return_date? If it cant, then fix the validations and the factories.rb file
  field :expected_return_date #TODO: Convert to type: Date
  field :project
  field :comments
  field :actions
  field :is_processed, type: Boolean, default: false

  validates_presence_of :emp_id, :emp_name, :departure_date, :place, :allow_blank => false

  class << self
    def get_json_to_populate(*args)
      # TODO: Can this be done with a 'group_by' and selecting only certain fields?
      outbound_travels = OutboundTravel.all
      args.inject({}) do |hash, field_name|
        hash[field_name] = outbound_travels.collect{|ot| ot[field_name].strip if ot[field_name].present?}.uniq.compact
        hash
      end
    end

    def set_as_processed(travel_id)
      outbound_travel = OutboundTravel.find(travel_id)
      outbound_travel.is_processed = true
      outbound_travel.save!
    end
  end

  def stay_duration
    date = self.return_date || DateHelper.date_from_str(self.expected_return_date)
    return (date - self.departure_date).to_i if date.present?
  end
end

app/controllers/outbound_travels_controller.rb
class OutboundTravelsController < ApplicationController
  include ExcelDataExporter

  HEADERS = [
    'PSID', 'Employee Name', 'Country of visit', 'Duration of Stay (apprx)',
    'Payroll effect in India', 'Departure date from India',
    'Foreign country payroll transfer date',
    'Return date to India', 'Payroll transfer date to India',
    'Expected return date', 'Project Code', 'Comment', 'Actions'
  ]

  def index
    @outbound_travels = OutboundTravel.desc(:departure_date).page(params[:page]).per(default_per_page)
    @outbound_travels = @outbound_travels.where({:departure_date.gte => params[:departure_date].try(:to_time)}) if !params[:departure_date].blank?
    # TODO: Name search should use like?
    @outbound_travels = @outbound_travels.any_of({emp_id: params[:emp_id].to_i}, {emp_name: params[:name]}) if !params[:emp_id].blank? || !params[:name].blank?
  end

  def show
    @outbound_travel = OutboundTravel.find(params[:id])
  end

  def new
    @outbound_travel = OutboundTravel.new
  end

  def edit
    @outbound_travel = OutboundTravel.find(params[:id])
  end

  def create
    @outbound_travel = OutboundTravel.new(params[:outbound_travel])
    if @outbound_travel.save
      redirect_to(outbound_travel_path(:id => @outbound_travel.id), :flash => {:success => 'Outbound travel was successfully created.'})
    else
      render :action => "new"
    end
  end

  def update
    @outbound_travel = OutboundTravel.find(params[:id])
    if @outbound_travel.update_attributes(params[:outbound_travel])
      redirect_to(outbound_travel_path(:id => @outbound_travel.id), :flash => {:success => 'Outbound travel was successfully updated.'})
    else
      render :action => "edit"
    end
  end

  def destroy
    @outbound_travel = OutboundTravel.find(params[:id])
    # TODO: What happens if the destroy fails?
    @outbound_travel.destroy
    redirect_to(outbound_travels_path, :flash => {:success => 'Outbound travel was successfully deleted.'})
  end

  def export
    export_xls(OutboundTravel.all, HEADERS, :model => OutboundTravel)
  end

  def data_to_suggest
    render :json => OutboundTravel.get_json_to_populate('place', 'payroll_effect', 'project')
  end

  def update_field
    @outbound_travel = OutboundTravel.find(params[:id])
    @outbound_travel.update_attributes(params[:name] => params[:value])
    render :nothing => true
  end

  def get_recent
    # TODO: What logic is this?
    @outbound_travels = OutboundTravel.where(:comments => nil).page(params[:page])
    render :index, :layout => 'tabs'
  end

  # TODO: Shouldnt this be merged in 'index' - search/filter/index are synonymous in REST
  def travels_without_return_date
    @outbound_travels = OutboundTravel.where(:return_date => nil).page(params[:page])
    render :index, :layout => 'tabs'
  end
end

app/views/outbound_travels/_form.html.erb
<%= form_for(@outbound_travel) do |f| %>
  <% if @outbound_travel.errors.any? %>
    <div id="error_explanation" class="errors">
      <h2><%= pluralize(@outbound_travel.errors.count, "error") %> prohibited this Outbound Travel from being saved:</h2>

      <ul>
        <% @outbound_travel.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="no_emp hide error">No employee found for given name.</div>
  <div class="fields">
    <table>
      <tr>
        <td class="text"><%= f.label :emp_id, 'Employee Id: ' %></td>
        <td><%= f.text_field :emp_id, :class => 'emp_id', :"data-href" => search_by_id_profiles_path %><span class="mandatory_mark">*</span></td>
      </tr>
      <tr>
        <td class="text"><%= f.label :emp_name, 'Employee Name: ' %></td>
        <td><%= f.text_field :emp_name, :class => 'emp_name', :"data-href" => search_by_name_profiles_path %><span class="mandatory_mark">*</span></td>
      </tr>
      <tr>
        <td class="text"><%= f.label :place, 'Country of Visit: ' %></td>
        <td><%= f.text_field :place %><span class="mandatory_mark">*</span></td>
      </tr>
      <tr>
        <td class="text"><%= f.label :travel_duration, 'Duration of Stay (apprx): ' %></td>
        <td><%= f.text_field :travel_duration %></td>
      </tr>
      <tr>
        <td class="text"><%= f.label :payroll_effect, 'Payroll effect in India: ' %></td>
        <td><%= f.text_field :payroll_effect %></td>
      </tr>
      <tr>
        <td class="text"><%= f.label :departure_date, 'Departure date from India: ' %></td>
        <td><%= f.text_field :departure_date, :class => 'date_picker' %><span class="mandatory_mark">*</span></td>
      </tr>
      <tr>
        <td class="text"><%= f.label :foreign_payroll_transfer, 'Foreign country payroll transfer date: ' %></td>
        <td><%= f.text_field :foreign_payroll_transfer %></td>
      </tr>
      <tr>
        <td class="text"><%= f.label :return_date, 'Return date to India: ' %></td>
        <td><%= f.text_field :return_date, :class => 'date_picker' %></td>
      </tr>
      <tr></tr>
      <tr>
        <td class="text"><%= f.label :return_payroll_transfer, 'Payroll transfer date to India: ' %></td>
        <td><%= f.text_field :return_payroll_transfer %></td>
      </tr>
      <tr>
        <td class="text"><%= f.label :expected_return_date, 'Expected return date: ' %></td>
        <td><%= f.text_field :expected_return_date %></td>
      </tr>
      <tr>
        <td class="text"><%= f.label :project, 'Project Code: ' %></td>
        <td><%= f.text_field :project %></td>
      </tr>
      <tr>
        <td class="text"><%= f.label :comments, 'Comment: ' %></td>
        <td><%= f.text_field :comments %></td>
      </tr>
      <tr>
        <td class="text"><%= f.label :actions, 'Actions: ' %></td>
        <td><%= f.text_field :actions %></td>
      </tr>
    </table>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
  <span class="mandatory_mark">*</span> <span class="red">Marked fields are mandatory</span> <br/>
<% end %>

<% content_for :page_js do %>
  <script>
    $(document).ready(function(){
      populateTravelFields();
    });
  </script>
<% end %>

app/views/outbound_travels/edit.html.erb
<h1>Editing outbound_travel</h1>

<%= render 'form' %>

<%= link_to('Show', @outbound_travel) %> |
<%= link_to('Back', outbound_travels_path) %>

app/views/outbound_travels/index.html.erb
<div class="right_align">
  <%= link_to image_tag("new_link.png") + "Create Outbound Travel", new_outbound_travel_path %>
</div>

<h1>Outbound Travels</h1>

<div class='saved_search'>
<span class='search_by'>Saved Searches:</span>
  <!-- TODO: Use the url helpers instead of hardcoding the url paths -->
  <%= link_to image_tag("search.png") + 'Recent Entries', '/outbound_travels/get_recent' %>
  <%= link_to image_tag("search.png") + 'Update Return Date', '/outbound_travels/travels_without_return_date' %>
</div>

<div class="no_emp hide error">No employee found for given name.</div>
<!-- TODO: This seems to be duplicated across all pages -->
<div>
  <%= form_tag(outbound_travels_path, :method => "get") do %>
    <span class="search_by">Search by:</span>

    <!-- TODO: This is the extra stuff -->
    <%= label_tag 'Departure From' %>
    <%= text_field_tag :departure_date, params[:departure_date], :class => 'date_picker' %>
    <span class="or_field">(or)</span>

    <%= label_tag 'Employee Name' %>:
    <%= text_field_tag :name, params[:name], :class => 'emp_name', :"data-href" => search_by_name_profiles_path %>
    <span class="or_field">(or)</span>
    <%= label_tag 'Employee Id' %>:
    <%= text_field_tag :emp_id, params[:emp_id], :class => 'emp_id', :"data-href" => search_by_id_profiles_path %>
    <%= submit_tag "Search", :name => nil %>
  <% end %>
</div>
<div class="right_align">
  <%= link_to(image_tag("excel.png") + "Export in Excel", export_outbound_travels_path(:format => :xls)) %>
</div>

<div>
  <%= paginate @outbound_travels %>
</div>

<table>
  <tr>
    <th>Id</th>
    <th>Name</th>
    <th>Country of Visit</th>
    <th>Duration of Stay</th>
    <th>Payroll effect in India</th>
    <th>Departure date</th>
    <th>Expected return Date</th>
    <th>Return date to India</th>
    <th>Comments</th>
    <th>&nbsp;</th>
    <th>&nbsp;</th>
  </tr>

  <% @outbound_travels.each do |outbound_travel| %>
    <tr id='<%= outbound_travel.id %>' class="<%= cycle("even", "odd") %>">
      <td><%= outbound_travel.emp_id %></td>
      <td><%= outbound_travel.emp_name %></td>
      <td><%= outbound_travel.place %></td>
      <td><%= outbound_travel.stay_duration %></td>
      <td class='edit' name='payroll_effect'><%= outbound_travel.payroll_effect %></td>
      <td class='edit_date_picker' name='departure_date'><%= DateHelper.date_fmt(outbound_travel.departure_date) %></td>
      <td class='edit_date_picker' name='expected_return_date'><%= DateHelper.date_fmt(DateHelper.date_from_str(outbound_travel.expected_return_date)) %></td>
      <td class='edit_date_picker' name='return_date'><%= DateHelper.date_fmt(outbound_travel.return_date) %></td>
      <td class='edit' name='comments'><%= outbound_travel.comments %></td>
      <td><% if (!outbound_travel.is_processed) %>
            <%= link_to 'Process Expense', load_by_travel_expense_settlement_path(:id => outbound_travel.id.to_s) %>
          <% end %>
      </td>
      <td><%= link_to 'Show', outbound_travel_path(:id => outbound_travel.id) %> |
          <%= link_to 'Edit', edit_outbound_travel_path(:id => outbound_travel.id) %> |
          <%= link_to 'Destroy', outbound_travel_path(:id => outbound_travel.id), :confirm => 'Are you sure?', :method => :delete %>
      </td>
    </tr>
  <% end %>
</table>
<br/>

<% content_for :page_js do %>
  <script>
    $(document).ready(function(){
      $('.edit_date_picker').editable(function(value, settings) {
        saveValue(value, settings, this);
      }, {
        type    : 'datepicker'
      });

      $('.edit').editable(function(value, settings) {
        saveValue(value, settings, this);
      }, {
        type   : 'text',
        submit : 'Save',
        cancel : 'Cancel'
      });

      // TODO: I think this is a bug that Ajit has discovered
      function saveValue(value, settings, _this){
        var obj_id = $(_this).parent().attr('id');
        var attr_name = $(_this).attr('name');
        $.ajax({
          type: 'POST',
          // TODO: Use url helpers rather than hardcoding the url
          url: '/outbound_travels/'+obj_id+'/update_field',
          data: {id: obj_id, name: attr_name, value: value},
          success: function(){
            location.reload();
          }
        })
      };
    });
  </script>
<% end %>

app/views/outbound_travels/new.html.erb
<h1>New Outbound Travel</h1>

<%= link_to(image_tag('back.png') + 'Back', outbound_travels_path) %>

<%= render 'form' %>

app/views/outbound_travels/show.html.erb
<h1>Outbound travel details</h1>
<h1 class="center_text"><%= @outbound_travel.emp_name %> (Emp Id: <%= @outbound_travel.emp_id %>)</h1>
<div>
<h3 class="center_text"> Travel Details </h3>
<table class="display_table">
<tr>
  <th>Place</th>
  <th>Travel Duration</th>
  <th>Departure Date</th>
  <th>Return Date</th>
</tr>
<tr>
  <td><%= @outbound_travel.place %></td>
  <td><%= @outbound_travel.travel_duration %></td>
  <td><%= DateHelper.date_fmt(@outbound_travel.departure_date) %></td>
  <td><%= DateHelper.date_fmt(@outbound_travel.return_date) %></td>
</tr>
</table>

<h3 class="center_text"> Payroll Details </h3>

<table class="display_table">
  <tr>
    <th>Payroll Effect</th>
    <th>Foreign Payroll Transfer</th>
    <th>Return Payroll Date</th>
  </tr>
  <tr>
    <td><%= @outbound_travel.payroll_effect %></td>
    <td><%= @outbound_travel.foreign_payroll_transfer %></td>
    <td><%= @outbound_travel.expected_return_date %></td>
  </tr>
</table>
</div>

<div class="center_text">
  <b>Commets : </b>
  <%= @outbound_travel.comments %><br/>

  <b>Actions :</b>
  <%= @outbound_travel.actions %><br/>
</div>

<%= link_to('Edit', edit_outbound_travel_path(@outbound_travel)) %> |
<%= link_to('Back', outbound_travels_path) %>