config/routes.rb
# TODO: Need to review and limit routes to only those methods that are implemented (eg using 'only')
# TODO: Need to review and set the method (POST vs GET va DELETE) appropriately
Mankatha::Application.routes.draw do
  root :to => 'expense_reimbursements#index'

  resources :users, :only => [:new, :create]
  resources :sessions, :only => [:new, :create, :destroy]     # TODO: Usually, you dont expose the session directly - its just a mechanism to validate and carry current login state

  resources :forex_payments do
    collection do
      get :export
      get :data_to_suggest
    end
    member do
      get :clone
    end
  end

  resources :forex_reports, :only => [:index] do
    collection do
      get :export
    end
  end

  resources :outbound_travels do
    collection do
      get :export
      get :data_to_suggest
      get :get_recent
      get :travels_without_return_date
    end
    member do
      post :update_field
    end
  end

  resources :expense_settlements do
    collection do
      get  :show_uploads
      post :generate_report
      post :file_upload
      post :delete_cash_handover
      delete :delete_expense
    end
    member do
      get :load_by_travel
      post :notify
      post :set_processed
    end
  end

  resources :consolidated_expenses, :only => [:index] do
    collection do
      get :export
      post :mark_processed_and_export
    end
  end

  resources :expense_reimbursements, :only => [:index, :show, :edit] do
    collection do
      post :process_reimbursement
    end
  end

  resources :profiles, :only => [] do
    collection do
      get :search_by_name
      get :search_by_id
    end
  end

  resources :reports, :only => [:index]
end

app/controllers/consolidated_expenses_controller.rb
class ConsolidatedExpensesController < ApplicationController
  include ExcelDataExporter

  HEADERS = ['Employee Id', 'Name', 'Bank A/C No', 'Cost In Home Currency', 'Deduction','Amount Payable After Deduction', 'Advance', 'Net Payable', 'Expense Report IDs' ,'Created By','Created At']
  COLUMNS = [:empl_id, :empl_name, :bank_account_no, :cost_in_home_currency, :deductions, :cost_in_home_currency, :advance, :reimbursable_amount, :expense_report_ids, :created_by, :created_at]

  def index
    @reimbursable_expense_reports = get_reimbursable_expenses
  end

  # TODO: Merge into the index method - based on the request format (which is already 'xls)
  def export
    render_excel(get_reimbursable_expenses)
  rescue => e
    redirect_to(consolidated_expenses_path, :flash => {:error => 'Could not fetch records'})
  end

  # TODO: Merge into the index method - based on the request format (which is already 'xls)
  def mark_processed_and_export
    completed_travel_reimbursements = ExpenseSettlement.mark_all_as_complete(params[:travel_reimbursements])
    completed_nontravel_reimbursements = ExpenseReimbursement.mark_all_as_complete(params[:nontravel_reimbursements])
    render_excel(completed_travel_reimbursements.concat(completed_nontravel_reimbursements))
  rescue => e
    logger.error "exception in excel export: " + e.inspect
    redirect_to(consolidated_expenses_path, :flash => {:error => 'Could not fetch records'})
  end

  private
  def get_reimbursable_expenses(mark_as_closed = false)
    reimbursable_expense_reports = ExpenseSettlement.get_reimbursable_expense_reports(mark_as_closed)
    reimbursable_expense_reports.concat(ExpenseReimbursement.get_reimbursable_expense_reports(mark_as_closed))
  end

  def render_excel(reimbursable_expenses)
    export_xls(reimbursable_expenses, HEADERS, {
      :exportable_fields => COLUMNS,
      :filename_prefix => "BankInstruction"
    })
  end
end

app/views/consolidated_expenses/index.html.erb
<br/>
<%= flash_message %>
<h1>Completed Expenses</h1>
<div>
<% if !@reimbursable_expense_reports.empty? %>
  <%= form_tag(mark_processed_and_export_consolidated_expenses_path(:format => :xls), :method => "post") do %>
  <table>
    <tr>
      <th>Select</th>
      <th>Employee Id</th>
      <th>Employee Name</th>
      <th>Expense Report Ids</th>
      <th>Bank Account No</th>
      <th>Amount</th>
    </tr>
    <% @reimbursable_expense_reports.each do |reimbursable_expense|%>
      <tr class="<%= cycle("even", "odd") %>">
        <td><%= check_box_tag reimbursable_expense.type + '[]', reimbursable_expense.id %></td>
        <td><%= reimbursable_expense.empl_id %></td>
        <td><%= reimbursable_expense.empl_name %></td>
        <td><%= reimbursable_expense.expense_report_ids %></td>
        <td><%= reimbursable_expense.bank_account_no %></td>
        <td><%= number_with_precision(reimbursable_expense.reimbursable_amount, :precision => 2) %></td>
      </tr>
    <% end %>
    <tr>
      <td colspan="6">
          <%= submit_tag 'Mark Complete and Send to bank', :confirm => 'Are you sure you want to close all selected reimbursements and send to the bank?' %>
      </td>
    </tr>
  <% end %>
  </table>
<% end %>
</div>