config/routes.rb
# TODO: Need to review and limit routes to only those methods that are implemented (eg using 'only')
# TODO: Need to review and set the method (POST vs GET va DELETE) appropriately
Mankatha::Application.routes.draw do
  root :to => 'expense_reimbursements#index'

  resources :users, :only => [:new, :create]
  resources :sessions, :only => [:new, :create, :destroy]     # TODO: Usually, you dont expose the session directly - its just a mechanism to validate and carry current login state

  resources :forex_payments do
    collection do
      get :export
      get :data_to_suggest
    end
    member do
      get :clone
    end
  end

  resources :forex_reports, :only => [:index] do
    collection do
      get :export
    end
  end

  resources :outbound_travels do
    collection do
      get :export
      get :data_to_suggest
      get :get_recent
      get :travels_without_return_date
    end
    member do
      post :update_field
    end
  end

  resources :expense_settlements do
    collection do
      get  :show_uploads
      post :generate_report
      post :file_upload
      post :delete_cash_handover
      delete :delete_expense
    end
    member do
      get :load_by_travel
      post :notify
      post :set_processed
    end
  end

  resources :consolidated_expenses, :only => [:index] do
    collection do
      get :export
      post :mark_processed_and_export
    end
  end

  resources :expense_reimbursements, :only => [:index, :show, :edit] do
    collection do
      post :process_reimbursement
    end
  end

  resources :profiles, :only => [] do
    collection do
      get :search_by_name
      get :search_by_id
    end
  end

  resources :reports, :only => [:index]
end

app/controllers/expense_settlement_controller.rb
require 'mongoid'
require 'helpers/expense_report_importer'

class ExpenseSettlementController < ApplicationController
  FOREX_PAYMENT_DATES_PADDED_BY=15
  EXPENSE_DATES_PADDED_BY=5

  def index
    default_per_page = params[:per_page] || 20
    if !params[:empl_id].blank?
      # TODO: These are not being evaluated - but are used in the view as is?
      @expense_settlements = ExpenseSettlement.for_empl_id(params[:empl_id]).page(params[:page]).per(default_per_page)
    else
      # TODO: These are not being evaluated - but are used in the view as is?
      @expense_settlements = ExpenseSettlement.page(params[:page]).per(default_per_page)
    end
    render :layout => 'tabs'
  end

  def load_by_travel
    travel = OutboundTravel.find(params[:id])
    padded_dates(travel)
    create_settlement_report_from_dates(travel)
  end

  def edit
    settlement_from_db = ExpenseSettlement.find(params[:id])
    settlement_from_db.populate_instance_data
    @expenses_from_date = DateHelper.date_from_str(settlement_from_db.expense_from)
    @expenses_to_date = DateHelper.date_from_str(settlement_from_db.expense_to)
    @forex_from_date = DateHelper.date_from_str(settlement_from_db.forex_from)
    @forex_to_date = DateHelper.date_from_str(settlement_from_db.forex_to)
    create_settlement_report_from_dates(settlement_from_db.outbound_travel)
    @expense_report["id"] = settlement_from_db.id.to_s
    render 'load_by_travel'
  end

  def show
    @expense_report = ExpenseSettlement.find(params[:id])
    @expense_report.populate_instance_data
    render 'generate_report'
  end

  def generate_report
    outbound_travel = OutboundTravel.find(params[:travel_id])
    @expense_report = outbound_travel.find_or_initialize_expense_settlement
    @expense_report.update_attributes({:cash_handover => params[:cash_handover].to_i, :status => 'Generated Draft'}.merge(
                                      params.slice(:expenses, :forex_payments, :emp_name, :empl_id, :expense_from, 
                                                   :expense_to, :forex_from, :forex_to).symbolize_keys)
                                     )
    @expense_report.populate_instance_data
  end

  def set_processed
    expense_report = ExpenseSettlement.find(params[:id])
    expense_report.complete
    redirect_to outbound_travels_path
  end

  def notify
    expense_report = ExpenseSettlement.find(params[:id])
    expense_report.notify_employee
    # TODO: What if the save failed?
    flash[:success] = "Expense settlement e-mail successfully sent to '" + expense_report.profile.common_name + "'"
    redirect_to(:action => :index, :anchor => 'expense_settlement', :empl_id => expense_report.empl_id)
  end

  def upload
    @uploaded_files = UploadedExpense.desc(:created_at)
  end

  def file_upload
    require 'fileutils'
    @file_name = params[:file_upload][:my_file].original_filename
    if load_to_db
      flash[:success] = 'File: ' + @file_name + ' has been uploaded successfully'
    else
      flash[:error] = 'This file has already been uploaded'
    end
    redirect_to :action => 'upload'
  end

  private
  def load_to_db
    tmp = params[:file_upload][:my_file].tempfile
    file = File.join("public", @file_name)
    FileUtils.cp(tmp.path, file)
    success = ExpenseReportImporter.load_expense(file)
    FileUtils.rm(file)
    success
  end

  def padded_dates(travel)
    @expenses_from_date = params[:expense_from] ? DateHelper.date_from_str(params[:expense_from]) : travel.departure_date - EXPENSE_DATES_PADDED_BY
    @expenses_to_date = params[:expense_to] ? DateHelper.date_from_str(params[:expense_to]) : (travel.return_date ? (travel.return_date + EXPENSE_DATES_PADDED_BY) : nil)
    @forex_from_date = params[:forex_from] ? DateHelper.date_from_str(params[:forex_from]) : travel.departure_date - FOREX_PAYMENT_DATES_PADDED_BY
    @forex_to_date = params[:forex_to] ? DateHelper.date_from_str(params[:forex_to]) : travel.return_date
  end

  def create_settlement_report_from_dates(travel)
    # TODO: Is this an ARel call?
    processed_expenses = ExpenseSettlement.where(processed: true).for_empl_id(travel.emp_id.to_s).only(:expenses, :forex_payments).to_a
    processed_expense_ids = processed_expenses.collect(&:expenses).flatten
    processed_forex_ids = processed_expenses.collect(&:forex_payments).flatten

    expenses = Expense.fetch_for_employee_between_dates travel.emp_id, @expenses_from_date, @expenses_to_date, processed_expense_ids
    forex_payments = ForexPayment.fetch_for travel.emp_id, @forex_from_date, @forex_to_date, processed_forex_ids
    @all_currencies = forex_payments.collect(&:currency)
    @expense_report = {"expenses" => expenses,
                       "forex_payments" => forex_payments,
                       "empl_id" => travel.emp_id,
                       "travel_id" => travel.id.to_s}
  end
end

app/controllers/expense_settlements_controller.rb
class ExpenseSettlementsController < ApplicationController
  FOREX_PAYMENT_DATES_PADDED_BY=15
  EXPENSE_DATES_PADDED_BY=5

  def index
    criteria = !params[:empl_id].blank? ? ExpenseSettlement.for_empl_id(params[:empl_id]) : ExpenseSettlement
    # TODO: These are not being evaluated - but are used in the view as is?
    @expense_settlements = criteria.page(params[:page]).per(default_per_page)
  end

  def load_by_travel
    @travel = OutboundTravel.find(params[:id])
    padded_dates(@travel)
    create_settlement_report_from_dates(@travel.emp_id)
  end

  def edit
    settlement_from_db = ExpenseSettlement.load_with_deps(params[:id])
    @expenses_from_date = settlement_from_db.expense_from
    @expenses_to_date = settlement_from_db.expense_to
    @forex_from_date = settlement_from_db.forex_from
    @forex_to_date = settlement_from_db.forex_to
    create_settlement_report_from_dates(settlement_from_db.empl_id.to_i, settlement_from_db)
    render 'load_by_travel'
  end

  def show
    @expense_settlement = ExpenseSettlement.find_by_id_with_expenses_and_forex(params[:id])
    render 'generate_report'
  end

  def generate_report
    @expense_settlement = ExpenseSettlement.find_or_initialize(params[:expense_settlement][:id])
    @expense_settlement.update_attributes!({:cash_handovers => params[:expense_settlement][:cash_handovers_attributes],
                                           :status => ExpenseSettlement::GENERATED_DRAFT,
                                           :empl_id =>  params[:expense_settlement][:empl_id],
                                           :emp_name => params[:expense_settlement][:emp_name],
                                           :expense_from => DateHelper.date_from_str(params[:expense_from]),
                                           :expense_to => DateHelper.date_from_str(params[:expense_to]),
                                           :forex_from => DateHelper.date_from_str(params[:forex_from]),
                                           :forex_to => DateHelper.date_from_str(params[:forex_to]),
                                           :created_by => current_user.user_name
                                          }.merge(params.slice(:expenses, :forex_payments).symbolize_keys))
    @expense_settlement.cash_handovers.map(&:save!)

    if(!params[:expense_settlement][:outbound_travel_id].blank?)
      OutboundTravel.set_as_processed(params[:expense_settlement][:outbound_travel_id])
    end

    @expense_settlement.populate_instance_data
  end

  def set_processed
    is_processed = ExpenseSettlement.mark_as_complete(params[:id])

    redirect_to(outbound_travels_path, :flash => get_flash_message(is_processed,
                                                                  "Completed processing Travel settlement",
                                                                  "Failed to complete Travel settlement"))
  end

  def notify
    expense_report = ExpenseSettlement.find_and_notify_employee(params[:id])
    # TODO: What if the save or notify failed?
    redirect_to(expense_settlements_path, :flash => {:success => "Expense settlement e-mail successfully sent to '#{expense_report.employee_detail.try(:emp_name)}'"})
  end

  def show_uploads
    @uploaded_files = UploadedExpense.desc(:created_at)
  end

  def delete_cash_handover
    CashHandover.delete_all(conditions: {_id: BSON::ObjectId(params[:id])})
    render :nothing => true, :status => :ok
  end

  def file_upload
    require 'fileutils'
    @file_name = params[:file_upload][:my_file].original_filename
    inserted_record_count = load_to_db
    redirect_to(show_uploads_expense_settlements_path, :flash => get_flash_message(inserted_record_count > 0,
                                                              "Totally #{inserted_record_count} records from file #{@file_name} are been uploaded successfully",
                                                              'No records uploaded. Either this file has already been uploaded or all rows have errors'))
  end

  def delete_expense
    file_name = params[:file_name]
    no_of_rows_deleted = Expense.delete_all(conditions: {file_name: file_name})
    doc_deleted = UploadedExpense.delete_all(conditions: {file_name: file_name})
    redirect_to(show_uploads_expense_settlements_path, :flash => get_flash_message(no_of_rows_deleted > 0 && doc_deleted ==1,
                                                              "File: '#{file_name}' has been deleted successfully",
                                                              'No records deleted'))
  end

  private
  def load_to_db
    tmp = params[:file_upload][:my_file].tempfile
    file = File.join("public", @file_name)
    FileUtils.cp(tmp.path, file)
    return ExpenseImporter.new.load_expense(file,params[:file_upload][:is_new_type_expense]!="0")
  ensure
    FileUtils.rm(file)
  end

  def padded_dates(travel)
    @expenses_from_date = !params[:expense_from].blank? ? DateHelper.date_from_str(params[:expense_from]) : travel.departure_date - EXPENSE_DATES_PADDED_BY
    @expenses_to_date = !params[:expense_to].blank? ? DateHelper.date_from_str(params[:expense_to]) : (travel.return_date ? (travel.return_date + EXPENSE_DATES_PADDED_BY) : nil)
    @forex_from_date = !params[:forex_from].blank? ? DateHelper.date_from_str(params[:forex_from]) : travel.departure_date - FOREX_PAYMENT_DATES_PADDED_BY
    @forex_to_date = !params[:forex_to].blank? ? DateHelper.date_from_str(params[:forex_to]) : travel.return_date
  end

  def create_settlement_report_from_dates(empl_id, expense_settlement = nil)
    # TODO: Is this an ARel call?
    processed_expenses = ExpenseSettlement.load_processed_for(empl_id)
    processed_expense_hashes = processed_expenses.collect(&:expenses).flatten.compact
    processed_expense_ids = processed_expense_hashes.collect{|expense_hash| expense_hash['expense_id']}

    processed_forex_ids = processed_expenses.collect(&:forex_payments).flatten.compact

    @expenses = Expense.fetch_for_employee_between_dates(empl_id, @expenses_from_date, @expenses_to_date, processed_expense_ids)
    @forex_payments = ForexPayment.fetch_for(empl_id, @forex_from_date, @forex_to_date, processed_forex_ids)
    @applicable_currencies = ForexPayment.get_json_to_populate('currency')['currency']
    @payment_modes = [CashHandover::CASH, CashHandover::CREDIT_CARD]
    @has_cash_handovers = !expense_settlement.nil? && expense_settlement.cash_handovers.size() > 0
    @expense_settlement = expense_settlement || ExpenseSettlement.new(:id => nil,
                                                                  :empl_id => empl_id,
                                                                  :forex_payments => @forex_payments.collect(&:id),
                                                                  :expenses => @expenses.collect(&:id))
    @expense_settlement.cash_handovers << CashHandover.new if @expense_settlement.cash_handovers.empty?
  end

  def get_flash_message(flag, success_message, error_message)
    if(flag)
      return {:success => success_message}
    else
      return {:error => error_message}
    end
  end
end

app/views/expense_settlements/generate_report.html.erb
<%= render :partial => '/partial/expense_settlement/report' %>

<table id="report_buttons">
  <tr>
    <td>
      <div class="left_button">
        <%
        back_path = @expense_settlement.is_complete? || @expense_settlement.is_closed? ? expense_settlements_path : edit_expense_settlement_path(:id => @expense_settlement.id)
        %>
        <%= button_to('<< Back', back_path, :method => :get) %>
      </div>
    <td>
      <div class="right_button">
        <% if @expense_settlement.is_generated_draft? %>
          <%= button_to('Notify employee', notify_expense_settlement_path(:id => @expense_settlement.id.to_s)) %>
        <% end %>
      </div>
    </td>
  </tr>
</table>

app/views/expense_settlements/index.html.erb
<br/>
<%= flash_message %>
<h1>Expense Settlement</h1>
<!-- TODO: This seems to be duplicated across all pages -->
<div>
  <%= form_tag(expense_settlements_path, :method => "get") do %>
    <span class="search_by">Search by:</span>
    <%= label_tag 'Employee Name' %>:
    <%= text_field_tag :name, params[:name], :class => 'emp_name', :"data-href" => search_by_name_profiles_path %>
    <span class="or_field">(or)</span>
    <%= label_tag 'Employee Id' %>:
    <%= text_field_tag :empl_id, params[:empl_id], :class => 'emp_id', :"data-href" => search_by_id_profiles_path %>
    <%= submit_tag "Search", :name => nil %>
  <% end %>
</div>
<% if @expense_settlements %>
  <div>
    <%= paginate @expense_settlements %>
  </div>
  <table>
    <tr>
      <th>Employee Id</th>
      <th>Employee Name</th>
      <th>Expenses From Date</th>
      <th>Expenses To Date</th>
      <th>Amount</th>
      <th>Status</th>
      <th>Last Updated</th>
      <th>Action</th>
    </tr>
    <% @expense_settlements.each do |expense_settlement|
      expense_settlement.populate_instance_data
    %>
      <tr class="<%= cycle("even", "odd") %>">
        <td>
          <%
          back_path = !expense_settlement.is_editable? ? expense_settlement_path(:id => expense_settlement.id.to_s) : edit_expense_settlement_path(:id => expense_settlement.id.to_s)
          %>
          <%= link_to(expense_settlement.empl_id, back_path) %>
        </td>
        <td><%= expense_settlement.emp_name %></td>
        <td><%= DateHelper.date_fmt(expense_settlement.expense_from) %></td>
        <td><%= DateHelper.date_fmt(expense_settlement.expense_to) %></td>
        <td><%= number_with_precision(expense_settlement.get_receivable_amount, :precision => 2) %></td>
        <td><%= expense_settlement.status %></td>
        <td><%= DateHelper.date_fmt(expense_settlement.updated_at) %></td>
        <td>
          <% if expense_settlement.is_notified_employee? %>
            <%= button_to('Mark as Processed', set_processed_expense_settlement_path(:id => expense_settlement.id.to_s)) %>
          <% else %>
            <label>N/A</label>
          <% end %>
        </td>
      </tr>
    <% end %>
  </table>
<% end %>

app/views/expense_settlements/load_by_travel.html.erb
<%= form_for @expense_settlement, :url => expense_settlement_url('generate_report'), :method => 'post' do |settlement_form| %>

    <%= settlement_form.hidden_field :id, :value => @expense_settlement.id.to_s %>
    <%= settlement_form.hidden_field :empl_id %>
    <%= settlement_form.hidden_field :outbound_travel_id, :value => @travel.try{|t|t.id.to_s}%>
    <%= settlement_form.hidden_field :emp_name, :value => (@forex_payments.first.emp_name unless @forex_payments.first.nil?) %>
    <br/>

    <span class="heading">Forex Information</span>

    <div>
      <div style="display: inline-block; padding-right: 10px;">
        <h4>From Date</h4>
        <input type="text" id="forex_from" name="forex_from" class="date_picker refresh" value="<%= DateHelper.date_fmt(@forex_from_date) %>">
      </div>
      <div style="display: inline-block; padding-right: 10px;">
        <h4>To Date</h4>
        <input type="text" name="forex_to" id="forex_to" class="date_picker refresh" value="<%= DateHelper.date_fmt(@forex_to_date) %>">
      </div>
    </div>
    <table>
      <tr>
        <th>&nbsp;</th>
        <th>Employee Id</th>
        <th>Name</th>
        <th>Issue Date</th>
        <th>Amount</th>
        <th>Currency</th>
        <th>Conversion Rate*</th>
        <th>Amount (INR)</th>
        <th>Place</th>
      </tr>
      <%
         forexes_avlbl = @forex_payments.present? && !@forex_payments.empty?
         if forexes_avlbl
          @forex_payments.each do |payment| %>
            <tr class="<%= cycle("even", "odd") %>">
              <td><%= check_box_tag 'forex_payments[]', payment.id.to_s, :checked => true %></td>
              <td><%= payment.emp_id %></td>
              <td><%= payment.emp_name %></td>
              <td><%= payment.issue_date %></td>
              <td class='amount'><%= payment.amount %></td>
              <td><%= payment.currency %></td>
              <td><%= number_with_precision(payment.conversion_rate, :precision => 2) %></td>
              <td class='inr'><%= payment.inr %></td>
              <td><%= payment.place %></td>
            </tr>
          <% end
             else %>
          <tr>
            <td colspan="7">No Forexes available around the chosen travel dates</td>
          </tr>
      <% end %>
    </table>
    <div class='right_button'>
      <h3> Calculated conversion rate: </span><span id='final_conversion_rate'></span></h3>
    </div>
    <div>* Rounded off to two decimal places.</div><br/>
    <span class="heading">Expenses</span>

    <div>
      <div style="display: inline-block; padding-right: 10px;">
        <h4>From Date</h4>
        <input type="text" id="expense_from" name="expense_from" class="date_picker refresh" value="<%= DateHelper.date_fmt(@expenses_from_date) %>">
      </div>
      <div style="display: inline-block; padding-right: 10px;">
        <h4>To Date</h4>
        <input type="text" id="expense_to" name="expense_to" class="date_picker refresh" value="<%= DateHelper.date_fmt(@expenses_to_date) %>">
      </div>
    </div>
    <%
       expenses_avlbl = @expenses.present? && !@expenses.empty?
       if expenses_avlbl
           expense_map = @expenses.group_by { |x| x[:expense_rpt_id].to_s } %>
        <div id="expense_report_accordion">
          <% expense_map.each do |report_id, expenses| %>
              <h2><a href="javascript:void(0);"><input type='checkbox' name='<%= report_id %>'><%= report_id %></a></h2>

              <div>
                <table id="<%= report_id %>_table">
                  <tr>
                    <th>&nbsp;</th>
                    <th>Expense Report Id</th>
                    <th>Project Code</th>
                    <th>Expense Date</th>
                    <th>Expense Type</th>
                    <th>Description</th>
                    <th>Amount</th>
                    <th>Payment Type</th>
                  </tr>
                  <% expenses.each do |expense| %>
                      <tr class="<%= cycle("even", "odd") %>">
                        <td><%= check_box_tag 'expenses[]', expense.id.to_s %></td>
                        <td><%= expense.expense_rpt_id %></td>
                        <td><%= expense.project %></td>
                        <td><%= DateHelper.date_fmt(expense.expense_date) %></td>
                        <td><%= expense.expense_type %></td>
                        <td><%= expense.description %></td>
                        <td><%= expense.original_cost %> <%= expense.original_currency %></td>
                        <td><%= expense.payment_type %></td>
                      </tr>
                  <% end %>
                </table>
              </div>
          <% end %>
        </div>
    <% else %>
        <table>
          <tr>
            <td colspan="8">No expenses available around the chosen travel dates</td>
          </tr>
        </table>
    <% end %>

    <div>
      <%= hidden_field_tag :applicable_currencies, @applicable_currencies %>
      <div class="cash_handover_selector <% if @has_cash_handovers %>hide <% end %>">
        <input type="button" value="Currency handovers" class="handover_selector"/>
      </div>
      <div class="cash_handover_section <% if !@has_cash_handovers %>hide <% end %>">
        <h4>Cash handed over by Employee: </h4>

        <table class="cash_handovers">
          <th>Amount</th>
          <th>Currency</th>
          <th>Conversion rate</th>
          <th>Payment mode</th>
          <th></th>
          <%= settlement_form.fields_for :cash_handovers do |handover_form| %>
              <tr class="cash_handover <%= cycle('even', 'odd') %>">
                <td>
                  <%= handover_form.text_field :amount, :autocomplete => "off", class: 'amount' %>
                </td>
                <td>
                  <%= handover_form.text_field :currency, :autocomplete => "off", class: 'handover_currency' %>
                </td>
                <td>
                  <%= handover_form.text_field :conversion_rate, :autocomplete => "off", class: 'conversion_rate' %>
                </td>
                <td>
                  <%= handover_form.select :payment_mode, @payment_modes, class: 'conversion_rate' %>
                </td>
                <td class="add_row_td">
                  <%= link_to image_tag("delete.png") + 'Delete', 'javaScript:void(0)', class: 'delete_row' %>
                </td>
              </tr>
          <% end %>
        </table>
        <%= link_to image_tag("new_link.png") + 'Add New Row', 'javaScript:void(0)', class: 'add_row' %>
      </div>
    </div>

    <br/><br/>

    <div class="right_button">
      <%= (forexes_avlbl || expenses_avlbl) ? submit_tag('Generate Report >>', class: 'generate_settlement') : '' %>
    </div>

<% end %>
<div class="left_button">
  <%= button_to('<< Back', outbound_travels_path, :method => :get) %>
</div>

app/views/expense_settlements/show_uploads.html.erb
<%= form_for :file_upload,:url => {:action => 'file_upload'}, :html => {:multipart => true}, :method => "post" do |f| %>
  <%= f.file_field :my_file %>
  <%= f.check_box :is_new_type_expense%>Is New type of expense?
  <%= f.submit "Upload" %>
<% end %>

<table id="uploaded_expenses_table">
  <tr>
    <th>File Name</th>
    <th>Uploaded At</th>
    <th>Delete</th>
  </tr>
  <% @uploaded_files.each do |file| %>
    <tr class="<%= cycle("even", "odd") %>">
      <td><%= file.file_name %></td>
      <td><%= file.created_at.strftime("%d-%b-%Y :: %H:%M:%S") %></td>
      <td><%= button_to 'Delete', delete_expense_expense_settlements_path(:file_name => file.file_name), {:method => :delete} %></td>
    </tr>
  <% end %>
</table>

app/views/expense_settlements/upload.html.erb
<%= form_for :file_upload,:url => {:action => 'file_upload'}, :html => {:multipart => true}, :method => "post" do |f| %>
  <%= f.file_field :my_file %>
  <%= f.submit "Upload" %>
<% end %>

<table id="uploaded_expenses_table">
  <tr>
    <th>File Name</th>
    <th>Uploaded At</th>
  </tr>
  <% @uploaded_files.each do |file| %>
    <tr class="<%= cycle("even", "odd") %>">
      <td><%= file.file_name %></td>
      <td><%= file.created_at.strftime("%d-%b-%Y :: %H:%M:%S") %></td>
    </tr>
  <% end %>
</table>